Make session#create response work with Turbo Drive enabled
Turbo Drive expects a form response to have HTTP status 422 or be a
303 redirect. Therefore change the response of session#create:

- when no resource found, render :new with HTTP status 422
- when found, redirect to root_path with HTTP status 303

This assumes that the application has a root_path defined.

Previously, an application with Turbo would show the session#new form
after submit unchanged and with this error in the javascript console:

    Error: Form responses must redirect to another location